@include('frontend.layouts.includes.header')
@include('frontend.layouts.includes.floating')
@yield('main-content')
@include('frontend.layouts.includes.search')
@include('frontend.layouts.includes.footer')
